apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-exemplo
spec:
  template:
    metadata:
      name: replicaset-exemplo
      labels:
        app: replicaset-01
    spec:
      containers:
        - name: nginx
          image:  niginx:stable
          ports:
            - containerPort:  80
          resources:
            limits:
              cpu:  "1"
              memory: "400Mi"
  replicas: 2
  selector:
    matchLabels:
      app: replicaset-01